package com.soho3q.cms.dal.dataobj;

import java.util.Date;

public class CmsChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.channel_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.description
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.status
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.css_file
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String cssFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.channel_id
     *
     * @return the value of cms_channel.channel_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.channel_id
     *
     * @param channelId the value for cms_channel.channel_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.name
     *
     * @return the value of cms_channel.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.name
     *
     * @param name the value for cms_channel.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.description
     *
     * @return the value of cms_channel.description
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.description
     *
     * @param description the value for cms_channel.description
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.status
     *
     * @return the value of cms_channel.status
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.status
     *
     * @param status the value for cms_channel.status
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.css_file
     *
     * @return the value of cms_channel.css_file
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getCssFile() {
        return cssFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.css_file
     *
     * @param cssFile the value for cms_channel.css_file
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCssFile(String cssFile) {
        this.cssFile = cssFile == null ? null : cssFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.creator
     *
     * @return the value of cms_channel.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.creator
     *
     * @param creator the value for cms_channel.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.create_time
     *
     * @return the value of cms_channel.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.create_time
     *
     * @param createTime the value for cms_channel.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.updater
     *
     * @return the value of cms_channel.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.updater
     *
     * @param updater the value for cms_channel.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.last_update_time
     *
     * @return the value of cms_channel.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.last_update_time
     *
     * @param lastUpdateTime the value for cms_channel.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}