package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.RebatesBonus;
import com.office.rebates.dal.dataobj.RebatesBonusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebatesBonusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int countByExample(RebatesBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int deleteByExample(RebatesBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int deleteByPrimaryKey(Long bonusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int insert(RebatesBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int insertSelective(RebatesBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    List<RebatesBonus> selectByExample(RebatesBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    RebatesBonus selectByPrimaryKey(Long bonusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") RebatesBonus record, @Param("example") RebatesBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByExample(@Param("record") RebatesBonus record, @Param("example") RebatesBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByPrimaryKeySelective(RebatesBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByPrimaryKey(RebatesBonus record);
}