package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.RebatesOrderItem;
import com.office.rebates.dal.dataobj.RebatesOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebatesOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int countByExample(RebatesOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int deleteByExample(RebatesOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int deleteByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int insert(RebatesOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int insertSelective(RebatesOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    List<RebatesOrderItem> selectByExample(RebatesOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    RebatesOrderItem selectByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") RebatesOrderItem record, @Param("example") RebatesOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByExample(@Param("record") RebatesOrderItem record, @Param("example") RebatesOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByPrimaryKeySelective(RebatesOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order_item
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByPrimaryKey(RebatesOrderItem record);
}