package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.RebatesOrder;
import com.office.rebates.dal.dataobj.RebatesOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebatesOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int countByExample(RebatesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int deleteByExample(RebatesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int insert(RebatesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int insertSelective(RebatesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    List<RebatesOrder> selectByExample(RebatesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    RebatesOrder selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") RebatesOrder record, @Param("example") RebatesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByExample(@Param("record") RebatesOrder record, @Param("example") RebatesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByPrimaryKeySelective(RebatesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Thu Dec 31 10:57:09 CST 2015
     */
    int updateByPrimaryKey(RebatesOrder record);
}