package com.soho3q.cms.dal.dao;

import com.soho3q.cms.dal.dataobj.CmsKey;
import com.soho3q.cms.dal.dataobj.CmsKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int countByExample(CmsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByExample(CmsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByPrimaryKey(Long keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insert(CmsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insertSelective(CmsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    List<CmsKey> selectByExample(CmsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    CmsKey selectByPrimaryKey(Long keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") CmsKey record, @Param("example") CmsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExample(@Param("record") CmsKey record, @Param("example") CmsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKeySelective(CmsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKey(CmsKey record);
}