package com.soho3q.cms.dal.dao;

import com.soho3q.cms.dal.dataobj.CmsTag;
import com.soho3q.cms.dal.dataobj.CmsTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int countByExample(CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByExample(CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByPrimaryKey(Long tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insert(CmsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insertSelective(CmsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    List<CmsTag> selectByExample(CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    CmsTag selectByPrimaryKey(Long tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") CmsTag record, @Param("example") CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExample(@Param("record") CmsTag record, @Param("example") CmsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKeySelective(CmsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKey(CmsTag record);
}