package com.office.rebates.dal.dataobj;

import java.util.Date;

public class RebatesOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.user_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.sales_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long salesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.soho3q_order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long soho3qOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.customer_mobile
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private String customerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.customer_name
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.customer_company
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private String customerCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.customer_alipay
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private String customerAlipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.porject_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private String porjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.porject_name
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private String porjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.checkin_date
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Date checkinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.checkout_date
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Date checkoutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.period_month
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer periodMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.period_week
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer periodWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.lease_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer leaseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.deposit_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer depositAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.create_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_order.last_update_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.order_id
     *
     * @return the value of rebates_order.order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.order_id
     *
     * @param orderId the value for rebates_order.order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.user_id
     *
     * @return the value of rebates_order.user_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.user_id
     *
     * @param userId the value for rebates_order.user_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.sales_id
     *
     * @return the value of rebates_order.sales_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getSalesId() {
        return salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.sales_id
     *
     * @param salesId the value for rebates_order.sales_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.soho3q_order_id
     *
     * @return the value of rebates_order.soho3q_order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getSoho3qOrderId() {
        return soho3qOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.soho3q_order_id
     *
     * @param soho3qOrderId the value for rebates_order.soho3q_order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setSoho3qOrderId(Long soho3qOrderId) {
        this.soho3qOrderId = soho3qOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.customer_mobile
     *
     * @return the value of rebates_order.customer_mobile
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.customer_mobile
     *
     * @param customerMobile the value for rebates_order.customer_mobile
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile == null ? null : customerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.customer_name
     *
     * @return the value of rebates_order.customer_name
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.customer_name
     *
     * @param customerName the value for rebates_order.customer_name
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.customer_company
     *
     * @return the value of rebates_order.customer_company
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public String getCustomerCompany() {
        return customerCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.customer_company
     *
     * @param customerCompany the value for rebates_order.customer_company
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCustomerCompany(String customerCompany) {
        this.customerCompany = customerCompany == null ? null : customerCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.customer_alipay
     *
     * @return the value of rebates_order.customer_alipay
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public String getCustomerAlipay() {
        return customerAlipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.customer_alipay
     *
     * @param customerAlipay the value for rebates_order.customer_alipay
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCustomerAlipay(String customerAlipay) {
        this.customerAlipay = customerAlipay == null ? null : customerAlipay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.porject_id
     *
     * @return the value of rebates_order.porject_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public String getPorjectId() {
        return porjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.porject_id
     *
     * @param porjectId the value for rebates_order.porject_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setPorjectId(String porjectId) {
        this.porjectId = porjectId == null ? null : porjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.porject_name
     *
     * @return the value of rebates_order.porject_name
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public String getPorjectName() {
        return porjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.porject_name
     *
     * @param porjectName the value for rebates_order.porject_name
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setPorjectName(String porjectName) {
        this.porjectName = porjectName == null ? null : porjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.checkin_date
     *
     * @return the value of rebates_order.checkin_date
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Date getCheckinDate() {
        return checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.checkin_date
     *
     * @param checkinDate the value for rebates_order.checkin_date
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCheckinDate(Date checkinDate) {
        this.checkinDate = checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.checkout_date
     *
     * @return the value of rebates_order.checkout_date
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Date getCheckoutDate() {
        return checkoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.checkout_date
     *
     * @param checkoutDate the value for rebates_order.checkout_date
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCheckoutDate(Date checkoutDate) {
        this.checkoutDate = checkoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.period_month
     *
     * @return the value of rebates_order.period_month
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getPeriodMonth() {
        return periodMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.period_month
     *
     * @param periodMonth the value for rebates_order.period_month
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setPeriodMonth(Integer periodMonth) {
        this.periodMonth = periodMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.period_week
     *
     * @return the value of rebates_order.period_week
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getPeriodWeek() {
        return periodWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.period_week
     *
     * @param periodWeek the value for rebates_order.period_week
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setPeriodWeek(Integer periodWeek) {
        this.periodWeek = periodWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.lease_amount
     *
     * @return the value of rebates_order.lease_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getLeaseAmount() {
        return leaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.lease_amount
     *
     * @param leaseAmount the value for rebates_order.lease_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setLeaseAmount(Integer leaseAmount) {
        this.leaseAmount = leaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.deposit_amount
     *
     * @return the value of rebates_order.deposit_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getDepositAmount() {
        return depositAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.deposit_amount
     *
     * @param depositAmount the value for rebates_order.deposit_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setDepositAmount(Integer depositAmount) {
        this.depositAmount = depositAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.create_time
     *
     * @return the value of rebates_order.create_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.create_time
     *
     * @param createTime the value for rebates_order.create_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_order.last_update_time
     *
     * @return the value of rebates_order.last_update_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_order.last_update_time
     *
     * @param lastUpdateTime the value for rebates_order.last_update_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}