package com.office.rebates.dal.dataobj;

import java.util.Date;

public class RebatesBonus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.bonus_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long bonusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.sales_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long salesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.soho3q_order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long soho3qOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.soho3q_order_num
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Long soho3qOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.lease_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer leaseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.bonus_before_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer bonusBeforeTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.bonus_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer bonusTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.bonus_after_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer bonusAfterTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.rebates_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Integer rebatesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.status
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.create_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.last_update_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_bonus.updater
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.bonus_id
     *
     * @return the value of rebates_bonus.bonus_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getBonusId() {
        return bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.bonus_id
     *
     * @param bonusId the value for rebates_bonus.bonus_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setBonusId(Long bonusId) {
        this.bonusId = bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.order_id
     *
     * @return the value of rebates_bonus.order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.order_id
     *
     * @param orderId the value for rebates_bonus.order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.sales_id
     *
     * @return the value of rebates_bonus.sales_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getSalesId() {
        return salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.sales_id
     *
     * @param salesId the value for rebates_bonus.sales_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.soho3q_order_id
     *
     * @return the value of rebates_bonus.soho3q_order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getSoho3qOrderId() {
        return soho3qOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.soho3q_order_id
     *
     * @param soho3qOrderId the value for rebates_bonus.soho3q_order_id
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setSoho3qOrderId(Long soho3qOrderId) {
        this.soho3qOrderId = soho3qOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.soho3q_order_num
     *
     * @return the value of rebates_bonus.soho3q_order_num
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Long getSoho3qOrderNum() {
        return soho3qOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.soho3q_order_num
     *
     * @param soho3qOrderNum the value for rebates_bonus.soho3q_order_num
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setSoho3qOrderNum(Long soho3qOrderNum) {
        this.soho3qOrderNum = soho3qOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.lease_amount
     *
     * @return the value of rebates_bonus.lease_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getLeaseAmount() {
        return leaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.lease_amount
     *
     * @param leaseAmount the value for rebates_bonus.lease_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setLeaseAmount(Integer leaseAmount) {
        this.leaseAmount = leaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.bonus_before_tax
     *
     * @return the value of rebates_bonus.bonus_before_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getBonusBeforeTax() {
        return bonusBeforeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.bonus_before_tax
     *
     * @param bonusBeforeTax the value for rebates_bonus.bonus_before_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setBonusBeforeTax(Integer bonusBeforeTax) {
        this.bonusBeforeTax = bonusBeforeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.bonus_tax
     *
     * @return the value of rebates_bonus.bonus_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getBonusTax() {
        return bonusTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.bonus_tax
     *
     * @param bonusTax the value for rebates_bonus.bonus_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setBonusTax(Integer bonusTax) {
        this.bonusTax = bonusTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.bonus_after_tax
     *
     * @return the value of rebates_bonus.bonus_after_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getBonusAfterTax() {
        return bonusAfterTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.bonus_after_tax
     *
     * @param bonusAfterTax the value for rebates_bonus.bonus_after_tax
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setBonusAfterTax(Integer bonusAfterTax) {
        this.bonusAfterTax = bonusAfterTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.rebates_amount
     *
     * @return the value of rebates_bonus.rebates_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Integer getRebatesAmount() {
        return rebatesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.rebates_amount
     *
     * @param rebatesAmount the value for rebates_bonus.rebates_amount
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setRebatesAmount(Integer rebatesAmount) {
        this.rebatesAmount = rebatesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.status
     *
     * @return the value of rebates_bonus.status
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.status
     *
     * @param status the value for rebates_bonus.status
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.create_time
     *
     * @return the value of rebates_bonus.create_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.create_time
     *
     * @param createTime the value for rebates_bonus.create_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.last_update_time
     *
     * @return the value of rebates_bonus.last_update_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.last_update_time
     *
     * @param lastUpdateTime the value for rebates_bonus.last_update_time
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_bonus.updater
     *
     * @return the value of rebates_bonus.updater
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_bonus.updater
     *
     * @param updater the value for rebates_bonus.updater
     *
     * @mbggenerated Mon Dec 28 10:52:03 CST 2015
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}