package com.soho3q.cms.dal.dataobj;

import java.util.Date;

public class CmsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.key_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Long keyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.channel_name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.tag_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String cmsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.description
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.key_type
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String keyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.enabled
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Byte enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_key.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.key_id
     *
     * @return the value of cms_key.key_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Long getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.key_id
     *
     * @param keyId the value for cms_key.key_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setKeyId(Long keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.channel_name
     *
     * @return the value of cms_key.channel_name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.channel_name
     *
     * @param channelName the value for cms_key.channel_name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.tag_id
     *
     * @return the value of cms_key.tag_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.tag_id
     *
     * @param tagId the value for cms_key.tag_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.cms_key
     *
     * @return the value of cms_key.cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getCmsKey() {
        return cmsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.cms_key
     *
     * @param cmsKey the value for cms_key.cms_key
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCmsKey(String cmsKey) {
        this.cmsKey = cmsKey == null ? null : cmsKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.name
     *
     * @return the value of cms_key.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.name
     *
     * @param name the value for cms_key.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.description
     *
     * @return the value of cms_key.description
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.description
     *
     * @param description the value for cms_key.description
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.key_type
     *
     * @return the value of cms_key.key_type
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.key_type
     *
     * @param keyType the value for cms_key.key_type
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType == null ? null : keyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.enabled
     *
     * @return the value of cms_key.enabled
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.enabled
     *
     * @param enabled the value for cms_key.enabled
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.creator
     *
     * @return the value of cms_key.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.creator
     *
     * @param creator the value for cms_key.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.create_time
     *
     * @return the value of cms_key.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.create_time
     *
     * @param createTime the value for cms_key.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.updater
     *
     * @return the value of cms_key.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.updater
     *
     * @param updater the value for cms_key.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_key.last_update_time
     *
     * @return the value of cms_key.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_key.last_update_time
     *
     * @param lastUpdateTime the value for cms_key.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}