package com.soho3q.cms.dal.dataobj;

import java.util.Date;

public class CmsTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.tag_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.channel_name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.color
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.tag_id
     *
     * @return the value of cms_tag.tag_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.tag_id
     *
     * @param tagId the value for cms_tag.tag_id
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.channel_name
     *
     * @return the value of cms_tag.channel_name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.channel_name
     *
     * @param channelName the value for cms_tag.channel_name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.name
     *
     * @return the value of cms_tag.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.name
     *
     * @param name the value for cms_tag.name
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.color
     *
     * @return the value of cms_tag.color
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.color
     *
     * @param color the value for cms_tag.color
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.creator
     *
     * @return the value of cms_tag.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.creator
     *
     * @param creator the value for cms_tag.creator
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.create_time
     *
     * @return the value of cms_tag.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.create_time
     *
     * @param createTime the value for cms_tag.create_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.updater
     *
     * @return the value of cms_tag.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.updater
     *
     * @param updater the value for cms_tag.updater
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.last_update_time
     *
     * @return the value of cms_tag.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.last_update_time
     *
     * @param lastUpdateTime the value for cms_tag.last_update_time
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}