package com.soho3q.cms.dal.dao;

import com.soho3q.cms.dal.dataobj.CmsChannel;
import com.soho3q.cms.dal.dataobj.CmsChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int countByExample(CmsChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByExample(CmsChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByPrimaryKey(Long channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insert(CmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insertSelective(CmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    List<CmsChannel> selectByExample(CmsChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    CmsChannel selectByPrimaryKey(Long channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") CmsChannel record, @Param("example") CmsChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExample(@Param("record") CmsChannel record, @Param("example") CmsChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKeySelective(CmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKey(CmsChannel record);
}