package com.soho3q.cms.dal.dao;

import com.soho3q.cms.dal.dataobj.CmsValueHistory;
import com.soho3q.cms.dal.dataobj.CmsValueHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsValueHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int countByExample(CmsValueHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByExample(CmsValueHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int deleteByPrimaryKey(Long valueHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insert(CmsValueHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int insertSelective(CmsValueHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    List<CmsValueHistory> selectByExample(CmsValueHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    CmsValueHistory selectByPrimaryKey(Long valueHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") CmsValueHistory record, @Param("example") CmsValueHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByExample(@Param("record") CmsValueHistory record, @Param("example") CmsValueHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKeySelective(CmsValueHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_value_history
     *
     * @mbggenerated Tue Nov 10 17:09:52 CST 2015
     */
    int updateByPrimaryKey(CmsValueHistory record);
}